// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty;

  ({
    constructor: function(options) {
      var k, v, _results;
      this.colors = [];
      _results = [];
      for (k in options) {
        if (!__hasProp.call(options, k)) continue;
        v = options[k];
        _results.push(this[k] = v);
      }
      return _results;
    },
    toRgbaString: function(color) {
      return 'rgba(' + color.join(',') + ',1)';
    }
  });

}).call(this);
